# Generated by Django 5.1.4 on 2024-12-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_complaints_mname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleexit',
            old_name='farem',
            new_name='feem',
        ),
    ]
